### ISSUE TITLE
user can view standings

### ISSUE THREAD

**Issue by twoosam** [twoosam/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view the season standings for all teams in the Premier League.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Displays all the teams in order from first to last.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/twoosam/ajax-project/assets/123339845/8a87604b-e099-434e-b72f-f2096faded61)
![image](https://github.com/twoosam/ajax-project/assets/123339845/918a03c7-0636-43f9-9159-954f21e53c31)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the header in a header-container so that it matches the figma example.
- [x] In the main container, create the HTML for the different tabs and current tab (grey and purple rows).
- [x] Create the HTML for a blank standings table. Give the table an id=standings-table.
- [x] Complete the standings page using the appropriate responsive layout classes.
  - [x] Write the CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
 - [x] In JavaScript, query the DOM for '#standings-table' element.
 - [x] Create a new XMLHttpRequest( ) object.
 - [x] Open( ) the object to send a 'GET' request to API-Football.
 - [x] Set object responseType to JSON.
 - [x] addEventListener( ) to execute a function when the response is eventually loaded.
 - [x] Loop through the response of the object.
 - [x] For each team object in the response, create a 'tr' element, and use the data from API-Football to fill out the 'td' elements with the:
   - [x] Team Logo
   - [x] Team Name
   - [x] Number of wins
   - [x] Number of draws
   - [x] Number of losses
   - [x] Total Points
 - [x] Append it to the '#standings-table' element.
 - [x] send( ) the request to begin loading the data from the server.  
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x] Test all functionality again in a private browsing session.
 - [x] Fix all errors.
