### ISSUE TITLE
user can view the top goal scorers

### ISSUE THREAD

**Issue by twoosam** [twoosam/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the top goal scorers of current Premier League season.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
By clicking the Top Scorers tab, the user will be able to see the top goal scorers and their amount in order from highest to lowest.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/twoosam/ajax-project/assets/123339845/e0554ec9-bb56-4db6-b97e-9c91b5c8e718)
![image](https://github.com/twoosam/ajax-project/assets/123339845/1b468bb5-e1c9-43ab-a708-0b3452a24886)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the main container, create the HTML for a blank unordered list and give it an id=top-scorers.
- [x] In main.js, create a function named viewSwap with a single parameter representing the name of the view to show. It should show the view whose name was provided as an argument.
- [x] Update the grey tab and add anchor tags to Standings and Top Scorers and style them like buttons to match the figma.
- [x] Create an event handler function that utilizes the viewSwap function to show the desired view.
- [x] Query the DOM for '#top-scorers' element.
- [x] Create a new XMLHttpRequest( ) object.
- [x] Open( ) the object to send a 'GET' request to API-Football.
- [x] addEventListener( ) to execute a function when the response is eventually loaded.
- [x] Loop through the response of the object.
- [x] For each players/topscorers object in the response, create an 'li' element, and use the API data to fill it with the:
   - [x] Player's image
   - [x] Player's name
   - [x] Number of goals 
- [x] Append it to the the '#top-scorers' element.
- [x] send( ) the request to begin the loading from the server.
- [x] Complete the Top Scorers page using the appropriate responsive layout classes.
   - [x] Write the CSS for mobile devices first.
   - [x] Adjust styling to fluidly adapt to desktop.
- [x] Remove all CSS styling that had no affect or was otherwise unecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
