### ISSUE TITLE
user can view the top assisters

### ISSUE THREAD

**Issue by twoosam** [twoosam/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the top goal assisters of current Premier League season. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking the Top Assisters tab, the user will be able to see the top goal assisters and their amount in order from highest to lowest.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/twoosam/ajax-project/assets/123339845/d76fa50f-c68b-41b1-988e-e428b4dbf500)
![image](https://github.com/twoosam/ajax-project/assets/123339845/610fbd12-3381-4a81-bdd2-42ef74c2fdd3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the main container, create the HTML for a blank unordered list and give it an id=top-assisters.
- [x] In main.js, update the viewSwap function to include if the string === 'top-assisters'.
- [x] Update the grey tab and add an anchor tag to Top Assisters and style them like buttons to match the previous Top Scorers and Standings Table.
- [x] Create an event handler function for the Top Assisters that utilizes the viewSwap function to show the Top Assisters view.
- [x] Query the DOM for '#top-assisters' element.
- [x] Create a new XMLHttpRequest( ) object.
- [x] Open( ) the object to send a 'GET' request to API-Football.
- [x] addEventListener( ) to execute a function when the response is eventually loaded.
- [x] Loop through the response of the object.
- [x] For each players/topassisters object in the response, create an 'li' element, and use the API data to fill it with the:
  - [x] Player's image
  - [x] Player's name
  - [x] Number of assists
- [x] Append it to the '#top-assisters' element.
- [x] send( ) the request to begin the loading from the server.
- [x] Complete the Top Assisters page using the appropriate responsive layout classes.
  - [x] Write the CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Remove all CSS styling that had no affect or was otherwise unecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
